# Generated by Django 4.1.1 on 2022-09-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='lose_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerdata',
            name='win_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
