# Generated by Django 4.1.1 on 2022-10-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_round_runnerup_alter_round_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='matches_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='matches_won',
            field=models.IntegerField(default=0),
        ),
    ]
