# Generated by Django 4.1.1 on 2022-10-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entry_bonus_entry_matches_lost_entry_matches_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='point2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='court',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='point1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
