# Generated by Django 4.1.1 on 2022-10-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_match_point2_alter_match_court_alter_match_point1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='played',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
