# Generated by Django 4.1.1 on 2022-10-14 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_match_played_alter_match_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='point1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='point2',
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.round'),
        ),
    ]
