# Generated by Django 4.1.1 on 2022-10-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_match_point1_remove_match_point2_match_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
